### PR TITLE
Changed the name of the extension used for BOM generation

### PR DESCRIPTION
**Pull request by adrianjgeorge**
Changed the name of the extension from `dependencyManagement` to `bomGenerator`. This removes a conflict with the spring boot plugin that was also trying to create an extension with that name. There were two tests failing for me locally before the change, and the same two tests fail in the same way after the change.

### CODE REVIEW

**Comment by adrianjgeorge** [comment]
That test failure is one of the two that were failing for me before and after the change.

**Comment by oreissig** [comment]
"bomGenerator" sounds to me like this plugin was all about generating BOMs, but that's only a tiny side feature of the whole thing. Most functionality is not specific to Maven BOMs at all.

**Comment by adrianjgeorge** [comment]
I agree that it is a side feature, and it's one that is getting in my way. I'd rather it be it's own plugin, but that is a much larger change. The extension in question is being used as part of bom generation, which in the maven xml takes the form of dependency management. It wasn't an unreasonable name, but it's causing me problems. What's worse is i'm pretty sure its being used for the same thing over on the spring boot side, and i don't care about it there either. I've got two plugins fighting each other to provide functionality I don't want.

**Comment by marqub** [comment]
I'm also interested by this change :) What is the status of the pull request?

**Comment by rspieldenner** [comment]
changed to nebulaDependencyManagement

**Comment by wilkystorm** [comment]
May I please see an example of how to use nebulaDependencyManagement? I am trying this and it is not working:
nebulaDependencyManagement {
   imports {
      mavenBom "my.company:my-bom:version"
    }
}

**Pull request closed without merging**
